[proxmox]
pve01
pve02
pve03
pve04

[linux]
dns01  ansible_host=192.168.1.20  ansible_user=jatkins
docker ansible_host=192.168.1.174 ansible_user=jatkins

[proxmox:vars]
ansible_user=root
ansible_python_interpreter=/usr/bin/python3
